# Tutorial here: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

language: android
sudo: required
jdk: oraclejdk8



env:
 global:
 - ANDROID_API=24
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=24.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
 

 
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL


 

before_install:

- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- openssl aes-256-cbc -K $encrypted_058af3642dc1_key -iv $encrypted_058af3642dc1_iv
  -in .keystore.enc -out .keystore -d
- npm install -g spacejam
- npm install -g cordova
- curl https://install.meteor.com/ | sh
- chmod +x gradlew
- ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
#Source: https://medium.com/@oldergod/constraint-layout-and-circleci-travis-d50342696d2
services:
- mongodb
script: spacejam test --driver-package practicalmeteor:mocha

keytool -genkey -alias your-app-name -keyalg RSA -keysize 2048 -validity 10000 
#requires ruby installation
gem install travis


travis encrypt-file .keystore --add

before_install:
- openssl aes-256-cbc -K $encrypted_058af3642dc1_key -iv $encrypted_058af3642dc1_iv
  -in .keystore.enc -out .keystore -d



before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"









 