# Tutorial here: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

language: android
sudo: required
jdk: oraclejdk8


env:
 global:
 - ANDROID_API=24
 #- EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=24.0.2
 #- ADB_INSTALL_TIMEOUT=5 # minutes
 
licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+
 
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 #- android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL


 

before_install:

- mkdir "$ANDROID_HOME/licenses" || true
#- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
#- ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
#Source: https://medium.com/@oldergod/constraint-layout-and-circleci-travis-d50342696d2


script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

before_deploy:

- cd app/build/outputs/apk/
#- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/Asif_key_store.jks -storepass "Mrperfect" -keypass "Mrperfect" app-release-unsigned.apk ExampleKeystoreAlias

# Verification
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk BasicCalculator.apk"
deploy:
  provider: releases
  file: BasicCalculator.apk
  skip_cleanup: true

  on:
    repo: asif-khan17/Android1
    tags: true
    jdk: oraclejdk8
    api_key:
    secure: "2e9372545d343a71d12670506d5d230b1b4aade2"
    
    



 