# Tutorial here: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

env:
  global:
  - secure: < a long string >
  - secure: < a long string >


language: android
sudo: required
jdk: oraclejdk8



env:
 global:
 - ANDROID_API=24
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=24.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
 

 
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL


 

before_install:

- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

- chmod +x gradlew
- ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
#Source: https://medium.com/@oldergod/constraint-layout-and-circleci-travis-d50342696d2



 


before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- travis encrypt-file .keystore --add

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"


before_deploy:
- meteor build $HOME --server server-url
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
# replace with your-apk-name leave release-unsigned.apk as it is
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $HOME/android/release-unsigned.apk your-apk-name -keystore $HOME/.keystore -storepass $storepass -keypass $keypass
# replace with your-apk-name leave release-unsigned.apk as it is
- "${ANDROID_HOME}/build-tools/22.0.1/zipalign 4 $HOME/android/release-unsigned.apk $HOME/android/your-apk-name.apk"



deploy:
  provider: releases
  api_key: "2e9372545d343a71d12670506d5d230b1b4aade2"
  # replace your-apk-name
  file: "$HOME/android/BasicCalculator.apk"
  skip_cleanup: true
  on:
tags: true



 