language: android 
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-24
 before_install:
 - chmod +x gradlew
 - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
 - export JAVA_HOME=$JAVA8_HOME
 after_success:
 - chmod +x ./upload-gh-pages.sh
 - ./upload-apk.sh
 script:
 - ./gradlew build
 
 
   #create a new directory that will contain out generated apk

  mkdir $HOME/buildApk/ 
  #copy generated apk from build folder to the folder just created

  cp -R app/build/outputs/apk/app-debug.apk $HOME/android/
  #go to home and setup git  

  cd $HOME
  git config --global user.email "asifkhan.ak95.ak@gmail.com"
  git config --global user.name "Asif_khan" 
  #clone the repository in the buildApk folder

  git clone --quiet --branch=master  https://Asif_khan:2e9372545d343a71d12670506d5d230b1b4aade2@github.com/asif-khan17/Android1  master > /dev/null
  #go into directory and copy data we're interested

  cd master  cp -Rf $HOME/android/* .
  #add, commit and push files

  git add -f .
  git remote rm origin
  git remote add origin https://Asif_khan:2e9372545d343a71d12670506d5d230b1b4aade2@github.com/asif-khan17/Android1.git
  git add -f .
  git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed [skip ci] "
  git push -fq origin master > /dev/null
  echo -e "Done\n"