
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.2
  - android-24
  
  
  
  

before_install:
- mkdir "$ANDROID_SDK/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
- chmod +x gradlew

script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"



before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"



deploy:

  provider: releases
  
  api_key:
    secure: JHNtPeuX7yqc61XN93+j3QaHVsmQRYJHrwfXqwYd1LKFSMzuwNKDW0sky+YEIw6fWl0WfP3733TZK+37I00gOgnULtxpo6Er+eg5GFPoOC60DmTJJWznJXfaPU69PKtNmiCENSM2yM8YPfSA90XUmKPNHBil0YPPDiRdArPlFYy/BhXwhWgejGuTYHg6uLNmFa04KWBWRrDlII3t9fGm4oo8YZn2lxg9SpoR+bjPb9J3/9YVbVqCKdiR3ZqPCjNLCnogl2BpzsJLQdilIXYdco3h34i8Br/AeyRSuaUNWFMvZntRS1UVPDDuhDU6E9ZpbxBsAN4aOLOfTMLTy2o1D9HmNTqewL6rFzF21HVjPqjtnISeTCnGm0jtG9jfxzQ0ImAaRPYxWRF/0WS5q492rWyX7KbUh2iqY5lie8Ugc1ggYecIDY51Qa6v13k0f4NuOV0LKipGp+zuGBoA9Et6iIoWSTcQb5yqb23R60uUK9IxGXut/DkMJUWeHZq/DNUDf0fiwwPNsjKVyXYMjWb4ShKsIxjJYI7eLDxl1MFITYt9d33lPhwViBIJ4kRPVP7/Mb7r3LvrIlvBbF3/IiDqLa5ur2VI5xhT3FNHJHzphSqR8lr1mp8DAMwUU9EfhwBGCmB3OO/Co3a8SNk1roTMej91hM2/YzLvODEUb+EKp9k=
  file: ./app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  file_glob: true
  on:
    branch: "master"
    repo: asif-khan17/Android1
    
